---
- name: Create jdk Directory
  file:
   path: "/{{ jboss_dir }}/java/1.8"
   state: directory
   recurse: yes
   mode: 0755

- name: Download Java Package
  shell: "./s3fetch.sh binaries {{ jdk8_file }} {{ download_location }}"
  args:
    chdir: "/tmp/"
    warn: false

- name: Install java
  unarchive:
   src: "{{ download_location }}/{{ jdk8_file }}"
   dest: "/{{ jboss_dir }}/java/1.8"
   copy: no